# Generated by Django 4.1.3 on 2024-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='numero',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
