# Generated by Django 4.1.3 on 2024-01-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacao', '0001_initial'),
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levantamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('id_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.agente')),
                ('id_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacao.operacao')),
            ],
        ),
    ]
