# Generated by Django 4.1.3 on 2024-02-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0004_alter_transferencia_id_operacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='id_agent',
        ),
    ]
