# Generated by Django 4.1.3 on 2024-01-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
    ]
