# Generated by Django 4.1.3 on 2024-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0005_alter_agente_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='token',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
