# Generated by Django 4.1.3 on 2024-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0010_alter_agente_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='token',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
