"""
Django settings for digitalwallet_restapi project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Carrega variáveis de ambiente de .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(a=zj)qu)o@w@%wttn!m&(wj1l(knbrq*(6(dxd_rp^*44y-80'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'utilizador',
    'agente',
    'cliente',
    'conta',
    'operacao',
    'deposito',
    'levantamento',
    'transferencia',
    'opt_module',
    'rest_framework',
    'rest_framework.authtoken'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digitalwallet_restapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digitalwallet_restapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'carteiradigital',
        'USER': os.getenv('USER_DEFAULT_DB'),
        'PASSWORD':os.getenv('PASS_DEFAULT_DB'),
        'HOST':os.getenv('HOST_DEFAULT_DB'),
        'PORT':os.getenv('PORT_DEFAULT_DB')
    },
    'otp_dbtemp': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tempcarteiradigital',
        'USER': os.getenv('USER_TEMP_DB'),
        'PASSWORD':os.getenv('PASS_TEMP_DB'),
        'HOST':os.getenv('HOST_TEMP_DB'),
        'PORT':os.getenv('PORT_TEMP_DB')
    }
}

#Roteadores de base de dados
DATABASE_ROUTERS = [
                    'opt_module.routers.OptmoduleRouter',
                    'utilizador.routers.DjangoContribRouter',
                    'cliente.routers.ClienteRouter',
                    'conta.routers.ContaRouter',
                    'agente.routers.AgentRouter',
                    'operacao.routers.OperacaoRouter',
                    'deposito.routers.DepositoRouter',
                    'levantamento.routers.LevantamentoRouter',
                    'transferencia.routers.TransferenciaRouter'
                    ]


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


