# Generated by Django 4.1.3 on 2024-02-08 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accontValidationOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(unique=True)),
                ('optcode', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='operacaoOPT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('optcode', models.IntegerField(unique=True)),
                ('id_temp', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Agente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(unique=True)),
                ('saldo', models.FloatField(default=0.0)),
                ('celular', models.CharField(default='', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(unique=True)),
                ('celular', models.CharField(default='', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('numero', models.CharField(max_length=100)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Deposito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_agent', models.IntegerField()),
                ('id_operacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Levantamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_agent', models.IntegerField()),
                ('id_operacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_agent', models.IntegerField()),
                ('id_operacao', models.IntegerField()),
                ('numero_conta', models.CharField(max_length=100)),
            ],
        ),
    ]
