# Generated by Django 4.1.3 on 2024-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_deposito',
            name='id_agent',
            field=models.IntegerField(default=0),
        ),
    ]
