# Generated by Django 4.1.3 on 2024-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt_module', '0002_alter_temp_deposito_id_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaoopt',
            name='id_temp',
            field=models.IntegerField(),
        ),
    ]
