# Generated by Django 4.1.3 on 2024-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt_module', '0003_alter_operacaoopt_id_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_conta',
            name='numero',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='temp_deposito',
            name='id_operacao',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='temp_levantamento',
            name='id_operacao',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='temp_transferencia',
            name='id_operacao',
            field=models.IntegerField(unique=True),
        ),
    ]
