# Generated by Django 4.1.3 on 2024-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opt_module', '0004_alter_temp_conta_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_transferencia',
            name='id_agent',
        ),
    ]
