# Generated by Django 4.1.3 on 2024-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt_module', '0005_remove_temp_transferencia_id_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_agente',
            name='token',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
