# Generated by Django 4.1.3 on 2024-01-04 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_operacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.conta')),
            ],
        ),
    ]
