# Generated by Django 4.1.3 on 2024-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
